### ISSUE TITLE
Implement FantasyLand ChainRec

### ISSUE THREAD

**Issue by Avaq** [Avaq/Fluture#23]
https://github.com/fantasyland/fantasy-land/pull/152

**Comment by safareli** [comment]
Here is [implementation](https://github.com/safareli/free/blob/e5fbbde2c50a1ec61968ec7c529aa3bb8ea51841/src/tailRec.js#L25-L98) of ChainRec for `folktale/data.task` with [tests](https://github.com/safareli/free/blob/e5fbbde2c50a1ec61968ec7c529aa3bb8ea51841/test/tailRecM.js)
(it's not quite correct as it is not handling cleanup stuff of the data.task but without that it works well)

**Comment by Avaq** [comment]
Thanks @safareli! Appreciate the example implementation. I'm going to have a play around with this, because I would like to gain a better understanding. Then I'll possibly create a PR if I manage to get something useful for us to review. :)

**Comment by Avaq** [comment]
I will be on holiday for two weeks. I probably won't get to this. Feel free to create that PR if you wish @safareli :)

**Comment by Avaq** [comment]
:information_source: I started work on this.
