### ISSUE TITLE
TypeError: Uncaught error: Future#fork expected the computation...

### ISSUE THREAD

**Issue by kurtmilam** [Avaq/Fluture#46]
This looks similar to this issue in Futurize: [Return void from computation](https://github.com/futurize/futurize/issues/43)

I'm getting this when I try to run the `fourInstableFutures` example from the Readme.md.

Here's the original code that throws the error (copied and pasted from Readme.md):
```
const fourInstableFutures = Array.from(Array(4).keys()).map(
  i => Future(
    (rej, res) => setTimeout(
      () => Math.random() > 0.8 ? rej('failed') : res(i),
      20
    )
  )
);

const stabalizedFutures = fourInstableFutures.map(Future.fold(S.Left, S.Right))

Future.parallel(2, stabalizedFutures).fork(console.error, console.log);
```

Putting `void` in front of `setTimeout` makes the error go away:
```
const fourInstableFutures = Array.from(Array(4).keys()).map(
  i => Future(
    (rej, res) => void setTimeout(
      () => Math.random() > 0.8 ? rej('failed') : res(i),
      20
    )
  )
);

const stabalizedFutures = fourInstableFutures.map(Future.fold(S.Left, S.Right))

Future.parallel(2, stabalizedFutures).fork(console.error, console.log);
```

**Comment by Avaq** [comment]
Thanks for the heads-up! That piece of the documentation has been written before cancellation was introduced. I'll update the example!
