### ISSUE TITLE
Very bad library, Not fantasyland compliant!!!!!!!!!!!!

### ISSUE THREAD

**Issue by masterpusher** [Avaq/Fluture#49]
sry bad joke

**Comment by davidchambers** [comment]
This issue is unproductive and, frankly, disrespectful. I suggest you close it, @Avaq.

@masterpusher, if you'd like to engage in a productive, respectful discussion please update the issue's title and description to explain the problem.

**Comment by Avaq** [comment]
I suggest @masterpusher closes it himself, and thinks about his behavior for a moment.
