### ISSUE TITLE
Allow wrapping node functions that expect more than one result argument.

### ISSUE THREAD

**Issue by brett-uaudio** [Avaq/Fluture#54]
I might be totally missing something, but I'm having trouble wrapping fs.read with Future.node. I think the reason is that fs.read expects a callback with three arguments: err, bytesRead, and the data buffer. When I console.log ...args in the chained function called, it only shows bytesRead in the array of arguments.

Am I way off? If not, is there anyway around this?

**Comment by brett-uaudio** [comment]
I think I solved it with something similar to:

    function read(fd, buf, off, len, pos) {
            return Future((rej, res) => {
                    fs.read(fd, buf, off, len, pos, (err, bytesRead, buffer) => {
                            if (err) rej(err);
                            res({ bytesRead, buffer });
                    });
                    return () => {};
            });
    }

Sorry for the noise: I hadn't noticed I could call Future manually.

**Comment by Avaq** [comment]
Hi @brett-uaudio. No worries, feel free to ask questions. For a quick response you can try to ask your question in one of the FP related gitter rooms: [sanctuary](https://gitter.im/sanctuary-js/sanctuary), [fantasy-land](https://gitter.im/fantasyland/fantasy-land) or [ramda](https://gitter.im/ramda/ramda). Many people there work with Fluture.

I will probably go on to add a `futurizeV` (for variadic) to [futurize](https://github.com/futurize/futurize) for your use-case. And yes, for any use-cases that are not solved by one of the helpers in Fluture or futurize you can simply use the Future constructor. :)
